### ISSUE TITLE
Drozer is not able to connect to Agent installed on Emulator-The 'drozer==2.3.4' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by SimarjeetK** [WithSecureLabs/drozer#339]
### Steps to reproduce
1.Start the session by adb forward tcp:31415 tcp:31415 after set up.
2. type .... drozer console connect in Terminal
3.

### Expected behaviour
It should prompt to confirm  the Android ID of the device you have connected to, along with the manufacturer, model
and Android software version. 

### Actual behaviour
raceback (most recent call last):
  File "/usr/local/bin/drozer", line 4, in <module>
    __import__('pkg_resources').run_script('drozer==2.3.4', 'drozer')
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'drozer==2.3.4' distribution was not found and is required by the application

### Environment

**Operating system**: MAS OS High Sieraa

**Java Version:** Java 1.8

**Android Version:** Oero

**Drozer Version:** 2.4.2

**Install Method:** Built from source/.deb/.exe/.. --- .egg file 

### Drozer Config
```
Contents of ~/.drozer_config
```

### Drozer Error Logs
```
Drozer error logs, ensure Drozer is launched in debug mode
$ drozer console connect --debug
```
Traceback (most recent call last):
  File "/usr/local/bin/drozer", line 4, in <module>
    __import__('pkg_resources').run_script('drozer==2.3.4', 'drozer')
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/simarjeetk/.virtualenvs/drozer/lib/python2.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'drozer==2.3.4' distribution was not found and is required by the application
### ADB Logs
```
ADB Logs - To capture:
adb logcat -c
adb logcat > drozer_error.log
```

**Comment by jueemudras1** [comment]
Hey, did you try installing and setting up Drozer?
Is it like an automated sandbox for android?

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/withsecurelabs/drozer
