### ISSUE TITLE
finduris

### ISSUE THREAD

**Issue by batutahibnu17** [WithSecureLabs/drozer#341]
Hello Dev,

I found a problem when I wante to do finduris

```
dz> run scanner.provider.finduris -a com.xxx.xxx.android
Scanning com.xxx.xxx.android...
/usr/bin/javac -cp /usr/local/lib/python2.7/dist-packages/drozer-2.4.3-py2.7.egg/drozer/lib/android.jar ZipUtil.java
/usr/local/lib/python2.7/dist-packages/drozer-2.4.3-py2.7.egg/drozer/lib/dx --dex --output 4a78a7a38b67b985beccf6efac92375b.apk ZipUtil.class

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0037.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:665)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:634)
	at com.android.dx.command.dexer.Main.access$600(Main.java:78)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:572)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:170)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:596)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:498)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:264)
	at com.android.dx.command.dexer.Main.run(Main.java:230)
	at com.android.dx.command.dexer.Main.main(Main.java:199)
	at com.android.dx.command.Main.main(Main.java:103)
...while parsing ZipUtil.class

1 error; aborting
drozer could not find or compile a required extension library.
```

**Comment by Yogehi** [comment]
we have a docker container now that should help with running drozer

https://hub.docker.com/r/fsecurelabs/drozer
