### ISSUE TITLE
protobuf update libprotobuf.so.28 -> libprotobuf.so.32

### ISSUE THREAD

**Issue by freedom1b2830** [WithSecureLabs/drozer#404]
### Steps to reproduce
1.adb install agent (ok)
2.drozer console connect (error)

### Actual behaviour
drozer console connect
```

Traceback (most recent call last):
  File "_drozer.py", line 30, in <module>
    __import__("drozer.cli.%s" % (sys.argv[1]))
  File "/usr/share/drozer/drozer/cli/console.py", line 8, in <module>
    from drozer.console import Console
  File "/usr/share/drozer/drozer/console/__init__.py", line 4, in <module>
    from drozer.console.console import Console
  File "/usr/share/drozer/drozer/console/console.py", line 5, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/share/drozer/pydiesel/api/__init__.py", line 9, in <module>
    from pydiesel.api.frame import Frame
  File "/usr/share/drozer/pydiesel/api/frame.py", line 3, in <module>
    from pydiesel.api.protobuf_pb2 import Message
  File "/usr/share/drozer/pydiesel/api/protobuf_pb2.py", line 4, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 48, in <module>
    from google.protobuf.pyext import _message
ImportError: libprotobuf.so.28: cannot open shared object file: No such file or directory
```
### Environment

**Operating system**:
Linux archlinux 6.1.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000 x86_64 GNU/Linux
**Java Version:**
```
local/jdk11-openjdk 11.0.18.u10-2
local/jdk17-openjdk 17.0.6.u10-2
local/jdk8-openjdk 8.362.u09-1
local/jdk-openjdk 19.0.2.u7-2
local/jre11-openjdk 11.0.18.u10-2
local/jre11-openjdk-headless 11.0.18.u10-2
local/jre17-openjdk 17.0.6.u10-2
local/jre17-openjdk-headless 17.0.6.u10-2
local/jre8-openjdk 8.362.u09-1
local/jre8-openjdk-headless 8.362.u09-1
local/jre-openjdk 19.0.2.u7-2
local/jre-openjdk-headless 19.0.2.u7-2
local/openjdk11-doc 11.0.18.u10-2
local/openjdk11-src 11.0.18.u10-2
local/openjdk17-doc 17.0.6.u10-2
local/openjdk17-src 17.0.6.u10-2
local/openjdk8-doc 8.362.u09-1
local/openjdk8-src 8.362.u09-1
local/openjdk-doc 19.0.2.u7-2
local/openjdk-src 19.0.2.u7-2
```
java -version
```
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)
```

**Android Version:**
8.1.0
**Drozer Version:** 
2.4.4-9
**Install Method:** 
blackarch repo
### Drozer Config
file not created...

![DeepinScreenshot_выберите-область_20230220235843](https://user-images.githubusercontent.com/102818470/220215286-fba9640f-d96b-42ca-9a81-33f2b63a59b4.png)

**Comment by Yogehi** [comment]
![image](https://user-images.githubusercontent.com/10925671/222906063-31842fdb-6da8-4925-a229-074c7aab0d02.png)
